#!/bin/bash

rm -rf build
clear

if [[ "$OSTYPE" == "darwin"* ]]; then
    CFLAGS="-Wno-unused-command-line-argument -Wno-deprecated-declarations -I./lib/ $(pkg-config --cflags glfw3 glew) -lm"
    LDFLAGS="-Wno-unused-command-line-argument $(pkg-config --libs glfw3 glew) -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo"
else
    CFLAGS="-I./lib/ -lglfw -lGL -lGLEW -lGLU -lm"
    LDFLAGS="-lglfw -lGL -lGLEW -lGLU -lm"
fi

BUILDDIR='build'

FILES=`find src -name '*.c'`

for FILE in $FILES
do
    DIRECTORY="${FILE%/*}"

    echo "Compiling: $FILE"

    mkdir -p $BUILDDIR/$DIRECTORY

    gcc -c $FILE -o $BUILDDIR/$FILE.o $CFLAGS
done

OBJECTS=`find build -name '*.o'`

gcc $OBJECTS -o engine $LDFLAGS
