#ifndef UNIVERSE_CONFIG_H
#define UNIVERSE_CONFIG_H

#define UNIVERSE_LENGTH 100.0f
#define UNIVERSE_WIDTH  100.0f
#define UNIVERSE_HEIGHT 100.0f

#define UNIVERSE_SIZE (float) (UNIVERSE_LENGTH * UNIVERSE_WIDTH * UNIVERSE_HEIGHT)

#endif